/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class mDaftarMotor extends javax.swing.JFrame {
public static int statusCari = 0;
    /**
     * Creates new form mDaftarMotor
     */
    public mDaftarMotor() {
        initComponents();
        showData();
    }
    private void showData(){
        DefaultTableModel tabelM = new DefaultTableModel();
     tabelM.addColumn("Kode Motor");
     tabelM.addColumn("Nama Motor");
     tabelM.addColumn("Warna");
     tabelM.addColumn("Tahun");
     tabelM.addColumn("Merk");
     tabelM.addColumn("Harga");
     tabelM.addColumn("Username Penginput");
     
     try{
         String sql = "SELECT * FROM daftarmotor";
         java.sql.Connection conn = (Connection)koneksi.koneksiDB.myDB();
         java.sql.Statement stm = conn.createStatement();
         java.sql.ResultSet rs = stm.executeQuery(sql);
         while(rs.next())
         {
             tabelM.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),});
         }tabelMotor.setModel(tabelM);
     }catch(SQLException ex){
         JOptionPane.showMessageDialog(rootPane, "Gagal memuat!"+ex.getMessage());
     }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tCari = new javax.swing.JTextField();
        tbCari = new javax.swing.JButton();
        tbLihat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMotor = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tbBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(840, 460));
        setMinimumSize(new java.awt.Dimension(840, 460));
        setResizable(false);
        setSize(new java.awt.Dimension(840, 460));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel2.setMaximumSize(new java.awt.Dimension(840, 460));
        jPanel2.setMinimumSize(new java.awt.Dimension(840, 460));
        jPanel2.setPreferredSize(new java.awt.Dimension(840, 460));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cari Merk Motor");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 160, -1));

        tCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(tCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 120, -1));

        tbCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbCari.setText("Cari");
        tbCari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCariActionPerformed(evt);
            }
        });
        jPanel2.add(tbCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 110, 30));

        tbLihat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbLihat.setText("Cetak");
        tbLihat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbLihatActionPerformed(evt);
            }
        });
        jPanel2.add(tbLihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 80, 30));

        tabelMotor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tabelMotor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode Motor", "Nama", "Warna", "Tahun", "Merk", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelMotor.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tabelMotor);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 730, 290));

        jPanel3.setBackground(new java.awt.Color(12, 36, 97));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DAFTAR MOTOR");

        tbBack.setBackground(new java.awt.Color(255, 77, 77));
        tbBack.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tbBack.setForeground(new java.awt.Color(255, 255, 255));
        tbBack.setText("KEMBALI");
        tbBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(319, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(151, 151, 151)
                .addComponent(tbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/transparent-black-png-3.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(830, 460));
        jLabel2.setMinimumSize(new java.awt.Dimension(830, 460));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 745, 430));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/glatarbelakang2.jpg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(840, 460));
        jLabel3.setMinimumSize(new java.awt.Dimension(840, 460));
        jLabel3.setPreferredSize(new java.awt.Dimension(840, 460));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCariActionPerformed
        // TODO add your handling code here:
        statusCari=1;

        if (tCari.getText().isEmpty()){
            statusCari = 0;
        }else if(statusCari==1){
            DefaultTableModel tabelMerk= new DefaultTableModel();
            tabelMerk.addColumn("No.");
            tabelMerk.addColumn("Kode Motor");
            tabelMerk.addColumn("Nama");
            tabelMerk.addColumn("Warna");
            tabelMerk.addColumn("Tahun");
            tabelMerk.addColumn("Merk");
            tabelMerk.addColumn("Harga");
            String cari = tCari.getText();
            try{
                //                int no=1;
                String sql = "Select * FROM daftarmotor WHERE merk_motor LIKE '"+cari+"%'";
                java.sql.Connection conn = (Connection)koneksi.koneksiDB.myDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                java.sql.ResultSet res = pstm.executeQuery(sql);
                while(res.next()){
                    tabelMerk.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
                }
                tabelMotor.setModel(tabelMerk);
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(rootPane, "Merk yang dicari tidak ada!");

            }
        }
    }//GEN-LAST:event_tbCariActionPerformed

    private void tbLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbLihatActionPerformed
        // TODO add your handling code here:
        this.hide();
        cetak_struk pembeli = new cetak_struk();
        pembeli.setVisible(true);
    }//GEN-LAST:event_tbLihatActionPerformed

    private void tbBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBackActionPerformed
        // TODO add your handling code here:
        this.hide();
        mLoginPembeli back = new mLoginPembeli();
        back.setVisible(true);
    }//GEN-LAST:event_tbBackActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mDaftarMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mDaftarMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mDaftarMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mDaftarMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mDaftarMotor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCari;
    private javax.swing.JTable tabelMotor;
    private javax.swing.JButton tbBack;
    private javax.swing.JButton tbCari;
    private javax.swing.JButton tbLihat;
    // End of variables declaration//GEN-END:variables
}
