/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code;


import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author USER
 */
public class mDPesanan extends javax.swing.JFrame {

    /**
     * Creates new form mTransaksi
     */
    public mDPesanan() {
        initComponents();
        showData();
        bersihkanlayar();
       
    }

    private void bersihkanlayar(){
        //Isi si pembeli
        tNo_Pesanan.setEnabled(false);
        tFirstName.setEnabled(false);
        tLastName.setEnabled(false);
        tUsername.setEnabled(false);
        tKodeMotor.setEnabled(false);
        tNamaMotor.setEnabled(false);
        tWarnaMotor.setEnabled(false);
        tTahunMotor.setEnabled(false);
        tHargaMotor.setEnabled(false);
        tJumlahBeli.setEnabled(false);
        tTotal.setEnabled(false);
        tMetodePembayaran.setEnabled(false);
        transfer.setEnabled(false);
        totalSisa.setEnabled(false);
        showData();
        tNo_Pesanan.setText("");
        tFirstName.setText("");
        tLastName.setText("");
        tUsername.setText("");
        tKodeMotor.setText("");
        tNamaMotor.setText("");
        tWarnaMotor.setText("");
        tTahunMotor.setText("");
        tHargaMotor.setText("");
        tJumlahBeli.setText("");
        tTotal.setText("");
        tMetodePembayaran.setText("");
        transfer.setText("");
        totalSisa.setText("");
       
   }
   
    
    private void showData(){
        
        DefaultTableModel tabelP = new DefaultTableModel(); 
        tabelP.addColumn("No.");
        tabelP.addColumn("First Name");
        tabelP.addColumn("Last Name");
        tabelP.addColumn("Username");
        tabelP.addColumn("Kode Motor");
        tabelP.addColumn("Nama Motor");
        tabelP.addColumn("Warna");
        tabelP.addColumn("Tahun");
        tabelP.addColumn("Harga");
        tabelP.addColumn("Jumlah");
        tabelP.addColumn("Total");
        tabelP.addColumn("Metode");
        tabelP.addColumn("Transfer");
        tabelP.addColumn("Kembalian");
        try{
           
            String sql = "SELECT * FROM tabel_pesan";
            java.sql.Connection conn = (Connection)koneksi.koneksiDB.myDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                tabelP.addRow(new Object[]{res.getInt(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10),res.getString(11),res.getString(12),res.getString(13),res.getString(14)});
                
            }tabelPemesanan.setModel(tabelP);
        }catch (SQLException ex){
            System.out.println("Error = " + ex.getMessage());
        }
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tbBack = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tNo_Pesanan = new javax.swing.JTextField();
        tFirstName = new javax.swing.JTextField();
        tLastName = new javax.swing.JTextField();
        tUsername = new javax.swing.JTextField();
        tJumlahBeli = new javax.swing.JTextField();
        tKodeMotor = new javax.swing.JTextField();
        tNamaMotor = new javax.swing.JTextField();
        tWarnaMotor = new javax.swing.JTextField();
        tTahunMotor = new javax.swing.JTextField();
        tHargaMotor = new javax.swing.JTextField();
        tTotal = new javax.swing.JTextField();
        tMetodePembayaran = new javax.swing.JTextField();
        totalSisa = new javax.swing.JTextField();
        tbHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPemesanan = new javax.swing.JTable();
        transfer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1060, 670));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(12, 36, 97));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DAFTAR PESANAN");

        tbBack.setBackground(new java.awt.Color(255, 77, 77));
        tbBack.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tbBack.setForeground(new java.awt.Color(255, 255, 255));
        tbBack.setText("KEMBALI");
        tbBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(422, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(197, 197, 197)
                .addComponent(tbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addComponent(tbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 90));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Username");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 90, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Fisrt Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Metode Pembayaran");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 210, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Nomor Pesanan");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Last Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 100, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Transfer Uang");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 160, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Kode Motor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 110, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Jumlah Beli");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 150, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Nama Motor");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 110, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Warna Motor");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 120, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Tahun");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 120, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Harga");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 140, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Total");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 160, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Total Sisa");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 160, -1));

        tNo_Pesanan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tNo_Pesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 190, -1));

        tFirstName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 190, -1));

        tLastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 190, -1));

        tUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 190, -1));

        tJumlahBeli.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tJumlahBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 210, -1));

        tKodeMotor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tKodeMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 110, -1));

        tNamaMotor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tNamaMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 190, -1));

        tWarnaMotor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tWarnaMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 190, -1));

        tTahunMotor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tTahunMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 190, -1));

        tHargaMotor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tHargaMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 160, 210, -1));

        tTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 240, 210, -1));

        tMetodePembayaran.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tMetodePembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, 150, -1));

        totalSisa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(totalSisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 370, 210, -1));

        tbHapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbHapus.setText("Hapus");
        tbHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapusActionPerformed(evt);
            }
        });
        jPanel1.add(tbHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, 130, 30));

        tabelPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPemesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPemesanan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 960, 220));

        transfer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(transfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 330, 180, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/transparent-black-png-3.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 980, 630));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/glatarbelakang2.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapusActionPerformed
        // TODO add your handling code here:
         try{
            String sql = "DELETE FROM tabel_pesan WHERE no ='"+tNo_Pesanan.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.koneksiDB.myDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Berhasil dihapus!");
            showData();
            bersihkanlayar();
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Gagal dihapus!"+ex.getMessage());
        }
    }//GEN-LAST:event_tbHapusActionPerformed

    private void tabelPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPemesananMouseClicked
        // TODO add your handling code here:
        int tb_pesan = tabelPemesanan.getSelectedRow();
        tNo_Pesanan.setText(tabelPemesanan.getValueAt(tb_pesan, 0).toString());
        tFirstName.setText(tabelPemesanan.getValueAt(tb_pesan, 1).toString());
        tLastName.setText(tabelPemesanan.getValueAt(tb_pesan, 2).toString());
        tUsername.setText(tabelPemesanan.getValueAt(tb_pesan, 3).toString());
        tKodeMotor.setText(tabelPemesanan.getValueAt(tb_pesan, 4).toString());
        tNamaMotor.setText(tabelPemesanan.getValueAt(tb_pesan, 5).toString());
        tWarnaMotor.setText(tabelPemesanan.getValueAt(tb_pesan, 6).toString());
        tTahunMotor.setText(tabelPemesanan.getValueAt(tb_pesan, 7).toString());
        tHargaMotor.setText(tabelPemesanan.getValueAt(tb_pesan, 8).toString());
        tJumlahBeli.setText(tabelPemesanan.getValueAt(tb_pesan, 9).toString());
        tTotal.setText(tabelPemesanan.getValueAt(tb_pesan, 10).toString());
        tMetodePembayaran.setText(tabelPemesanan.getValueAt(tb_pesan, 11).toString());
        transfer.setText(tabelPemesanan.getValueAt(tb_pesan, 12).toString());
        totalSisa.setText(tabelPemesanan.getValueAt(tb_pesan, 13).toString());
        
        
    }//GEN-LAST:event_tabelPemesananMouseClicked

    private void tbBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBackActionPerformed
        // TODO add your handling code here:
        this.hide();
        mLoginPegawai back = new mLoginPegawai();
        back.setVisible(true);
    }//GEN-LAST:event_tbBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mDPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mDPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mDPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mDPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mDPesanan().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tFirstName;
    private javax.swing.JTextField tHargaMotor;
    private javax.swing.JTextField tJumlahBeli;
    private javax.swing.JTextField tKodeMotor;
    private javax.swing.JTextField tLastName;
    private javax.swing.JTextField tMetodePembayaran;
    private javax.swing.JTextField tNamaMotor;
    private javax.swing.JTextField tNo_Pesanan;
    private javax.swing.JTextField tTahunMotor;
    private javax.swing.JTextField tTotal;
    private javax.swing.JTextField tUsername;
    private javax.swing.JTextField tWarnaMotor;
    private javax.swing.JTable tabelPemesanan;
    private javax.swing.JButton tbBack;
    private javax.swing.JButton tbHapus;
    private javax.swing.JTextField totalSisa;
    private javax.swing.JTextField transfer;
    // End of variables declaration//GEN-END:variables
}
