/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code;

/**
 *
 * @author USER
 */
public class mHome extends javax.swing.JFrame {

    /**
     * Creates new form mHome
     */
    public mHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPassword = new javax.swing.JTextField();
        textPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        textUsername = new javax.swing.JLabel();
        gtransparant = new javax.swing.JLabel();
        gbluebackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(640, 320));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 230, 40));

        textPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textPassword.setText("PASSWORD");
        getContentPane().add(textPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 110, 20));
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 230, 40));

        textUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textUsername.setText("USERNAME");
        getContentPane().add(textUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 110, 20));

        gtransparant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/gtrans1.png"))); // NOI18N
        getContentPane().add(gtransparant, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 540, 220));

        gbluebackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/glatarbelakang1.jpg"))); // NOI18N
        getContentPane().add(gbluebackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gbluebackground;
    private javax.swing.JLabel gtransparant;
    private javax.swing.JLabel textPassword;
    private javax.swing.JLabel textUsername;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
