/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code;

/**
 *
 * @author USER
 */
public class mLoginPegawai extends javax.swing.JFrame {

    /**
     * Creates new form mLoginPegawai
     */
    public mLoginPegawai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tbTambahMotor = new javax.swing.JButton();
        tbDaftarPegawai = new javax.swing.JButton();
        tbDaftarPesanan = new javax.swing.JButton();
        tbDaftarPembeli = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(644, 422));
        setMinimumSize(new java.awt.Dimension(644, 422));
        setResizable(false);

        jPanel2.setMaximumSize(new java.awt.Dimension(644, 422));
        jPanel2.setMinimumSize(new java.awt.Dimension(644, 422));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(12, 36, 97));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Home");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addContainerGap(543, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 90));

        tbTambahMotor.setBackground(new java.awt.Color(255, 56, 56));
        tbTambahMotor.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        tbTambahMotor.setForeground(new java.awt.Color(255, 255, 255));
        tbTambahMotor.setText("TAMBAH MOTOR");
        tbTambahMotor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbTambahMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTambahMotorActionPerformed(evt);
            }
        });
        jPanel2.add(tbTambahMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 210, 70));

        tbDaftarPegawai.setBackground(new java.awt.Color(255, 56, 56));
        tbDaftarPegawai.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        tbDaftarPegawai.setForeground(new java.awt.Color(255, 255, 255));
        tbDaftarPegawai.setText("DAFTAR PEGAWAI");
        tbDaftarPegawai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbDaftarPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDaftarPegawaiActionPerformed(evt);
            }
        });
        jPanel2.add(tbDaftarPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 210, 70));

        tbDaftarPesanan.setBackground(new java.awt.Color(255, 56, 56));
        tbDaftarPesanan.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        tbDaftarPesanan.setForeground(new java.awt.Color(255, 255, 255));
        tbDaftarPesanan.setText("DAFTAR PESANAN");
        tbDaftarPesanan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbDaftarPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDaftarPesananActionPerformed(evt);
            }
        });
        jPanel2.add(tbDaftarPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 210, 70));

        tbDaftarPembeli.setBackground(new java.awt.Color(255, 56, 56));
        tbDaftarPembeli.setFont(new java.awt.Font("Century Gothic", 1, 20)); // NOI18N
        tbDaftarPembeli.setForeground(new java.awt.Color(255, 255, 255));
        tbDaftarPembeli.setText("DAFTAR PEMBELI");
        tbDaftarPembeli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbDaftarPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDaftarPembeliActionPerformed(evt);
            }
        });
        jPanel2.add(tbDaftarPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 210, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/glatarbelakang2.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(644, 422));
        jLabel2.setMinimumSize(new java.awt.Dimension(644, 422));
        jLabel2.setPreferredSize(new java.awt.Dimension(644, 422));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbTambahMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTambahMotorActionPerformed
        // TODO add your handling code here:
        this.show();
        this.hide();
        mTambahMotor tambah = new mTambahMotor();
        tambah.setVisible(true);
    }//GEN-LAST:event_tbTambahMotorActionPerformed

    private void tbDaftarPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDaftarPegawaiActionPerformed
        // TODO add your handling code here:
         this.hide();
        mDaftarPegawai daftar = new mDaftarPegawai();
        daftar.setVisible(true);
    }//GEN-LAST:event_tbDaftarPegawaiActionPerformed

    private void tbDaftarPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDaftarPembeliActionPerformed
        // TODO add your handling code here:
        this.hide();
        mDaftarPembeli daftar = new mDaftarPembeli();
        daftar.setVisible(true);
    }//GEN-LAST:event_tbDaftarPembeliActionPerformed

    private void tbDaftarPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDaftarPesananActionPerformed
        // TODO add your handling code here:
        this.hide();
        mDPesanan daftar = new mDPesanan();
        daftar.setVisible(true);
    }//GEN-LAST:event_tbDaftarPesananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mLoginPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mLoginPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mLoginPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mLoginPegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mLoginPegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton tbDaftarPegawai;
    private javax.swing.JButton tbDaftarPembeli;
    private javax.swing.JButton tbDaftarPesanan;
    private javax.swing.JButton tbTambahMotor;
    // End of variables declaration//GEN-END:variables
}
