/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code;

/**
 *
 * @author USER
 */
public class mLoginPembeli extends javax.swing.JFrame {

    /**
     * Creates new form mLoginPembeli
     */
    public mLoginPembeli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tbDaftarMotor = new javax.swing.JButton();
        tbPesan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(644, 422));
        setMinimumSize(new java.awt.Dimension(644, 422));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(644, 422));
        jPanel1.setMinimumSize(new java.awt.Dimension(644, 422));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(12, 36, 97));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SELAMAT DATANG");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel4)
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 90));

        tbDaftarMotor.setBackground(new java.awt.Color(232, 65, 24));
        tbDaftarMotor.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tbDaftarMotor.setForeground(new java.awt.Color(255, 255, 255));
        tbDaftarMotor.setText("DAFTAR MOTOR");
        tbDaftarMotor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbDaftarMotor.setMaximumSize(new java.awt.Dimension(160, 150));
        tbDaftarMotor.setMinimumSize(new java.awt.Dimension(160, 150));
        tbDaftarMotor.setPreferredSize(new java.awt.Dimension(160, 150));
        tbDaftarMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbDaftarMotorActionPerformed(evt);
            }
        });
        jPanel1.add(tbDaftarMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 190, 100));

        tbPesan.setBackground(new java.awt.Color(232, 65, 24));
        tbPesan.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        tbPesan.setForeground(new java.awt.Color(255, 255, 255));
        tbPesan.setText("PESAN");
        tbPesan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbPesan.setMaximumSize(new java.awt.Dimension(160, 150));
        tbPesan.setMinimumSize(new java.awt.Dimension(160, 150));
        tbPesan.setPreferredSize(new java.awt.Dimension(160, 150));
        tbPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbPesanActionPerformed(evt);
            }
        });
        jPanel1.add(tbPesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 190, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/glatarbelakang2.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(644, 422));
        jLabel1.setMinimumSize(new java.awt.Dimension(644, 422));
        jLabel1.setPreferredSize(new java.awt.Dimension(644, 422));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbPesanActionPerformed
        // TODO add your handling code here:
        this.hide();
        mPesan pesan = new mPesan();
        pesan.setVisible(true);
    }//GEN-LAST:event_tbPesanActionPerformed

    private void tbDaftarMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbDaftarMotorActionPerformed
        // TODO add your handling code here:
        this.hide();
        mDaftarMotor pesan = new mDaftarMotor();
        pesan.setVisible(true);
    }//GEN-LAST:event_tbDaftarMotorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mLoginPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mLoginPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mLoginPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mLoginPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mLoginPembeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton tbDaftarMotor;
    private javax.swing.JButton tbPesan;
    // End of variables declaration//GEN-END:variables
}
