/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code;

import com.sun.istack.internal.logging.Logger;
import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import javax.swing.Timer;
import java.util.Locale;
import sun.util.logging.PlatformLogger;

/**
 *
 * @author USER
 */
public class mPesan extends javax.swing.JFrame {

    /**
     * Creates new form mTransaksi
     */
    public mPesan() {
        initComponents();
        getID();
        showData();
        bersihkanlayar();
       
    }
    int lastid;
    
    public final void getID(){
        try{
        String sql = "SELECT MAX(no) FROM tabel_pesan";
        java.sql.Connection conn =(Connection)koneksi.koneksiDB.myDB();
        java.sql.Statement st = conn.createStatement();
        java.sql.ResultSet rs = st.executeQuery(sql);
        
        if(rs.next()){
             lastid = rs.getInt(1);
             lastid++;
             tNo_Pesanan.setText(Integer.toString(lastid));
             
        }
        bersihkanlayar();
      
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
        
    }
    
    private void bersihkanlayar(){
        //Isi si pembeli
        tNo_Pesanan.setEnabled(false);
        tFirstName.setText("");
        tLastName.setText("");
        tUsername.setText("");
        tKodeMotor.setText("");
        tNamaMotor.setText("");
        tWarnaMotor.setText("");
        tTahunMotor.setText("");
        tHargaMotor.setText("");
        tJumlahBeli.setText("");
        tTotal.setText("");
        pilihPembayaran.setSelectedItem("Pilih");
        transfer.setText("");
        totalSisa.setText("");
        showData();
        
        tJumlahBeli.setEnabled(false);
        tbHitung.setEnabled(false);
        tTotal.setEnabled(false);
        pilihPembayaran.setEnabled(false);
        transfer.setEnabled(false);
        tbKirim.setEnabled(false);
        totalSisa.setEnabled(false);
        
        tNamaMotor.setEnabled(false);
        tWarnaMotor.setEnabled(false);
        tTahunMotor.setEnabled(false);
        tHargaMotor.setEnabled(false);
   }
   
    
    private void showData(){
        
        DefaultTableModel tabelP = new DefaultTableModel(); 
        tabelP.addColumn("No.");
        tabelP.addColumn("First Name");
        tabelP.addColumn("Last Name");
        tabelP.addColumn("Username");
        tabelP.addColumn("Kode Motor");
        tabelP.addColumn("Nama Motor");
        tabelP.addColumn("Warna");
        tabelP.addColumn("Tahun");
        tabelP.addColumn("Harga");
        tabelP.addColumn("Jumlah");
        tabelP.addColumn("Total");
        tabelP.addColumn("Metode");
        tabelP.addColumn("Transfer");
        tabelP.addColumn("Kembalian");
        try{
           
            String sql = "SELECT * FROM tabel_pesan";
            java.sql.Connection conn = (Connection)koneksi.koneksiDB.myDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                tabelP.addRow(new Object[]{res.getInt(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10),res.getString(11),res.getString(12),res.getString(13),res.getString(14)});
                
            }tabelPemesanan.setModel(tabelP);
        }catch (SQLException ex){
            System.out.println("Error = " + ex.getMessage());
        }
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tbHome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tNo_Pesanan = new javax.swing.JTextField();
        tbReset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tbCari = new javax.swing.JButton();
        tFirstName = new javax.swing.JTextField();
        tLastName = new javax.swing.JTextField();
        tUsername = new javax.swing.JTextField();
        tJumlahBeli = new javax.swing.JTextField();
        tKodeMotor = new javax.swing.JTextField();
        tNamaMotor = new javax.swing.JTextField();
        tWarnaMotor = new javax.swing.JTextField();
        tTahunMotor = new javax.swing.JTextField();
        tHargaMotor = new javax.swing.JTextField();
        tTotal = new javax.swing.JTextField();
        totalSisa = new javax.swing.JTextField();
        tbTambah = new javax.swing.JButton();
        tbLihat = new javax.swing.JButton();
        tbHapus = new javax.swing.JButton();
        tbHitung = new javax.swing.JButton();
        tbKirim = new javax.swing.JButton();
        pilihPembayaran = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPemesanan = new javax.swing.JTable();
        transfer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1060, 670));
        setMinimumSize(new java.awt.Dimension(1060, 670));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(12, 36, 97));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbHome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tbHome.setForeground(new java.awt.Color(102, 255, 255));
        tbHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8_back_to_64.png"))); // NOI18N
        tbHome.setText("Kembali");
        tbHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHomeMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("MENU PEMESANAN");

        tNo_Pesanan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tbReset.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbReset.setText("Reset");
        tbReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(tNo_Pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(130, 130, 130)
                .addComponent(tbReset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbHome)
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tbHome, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbReset, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tNo_Pesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 90));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Username");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 90, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Fisrt Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Metode Pembayaran");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 190, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Last Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 100, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Transfer Uang");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 140, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Kode Motor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 110, -1));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Jumlah Beli");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 130, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Nama Motor");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 110, -1));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Warna Motor");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 120, -1));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Tahun");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 120, -1));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Harga");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 120, -1));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Total");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 140, -1));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Total Sisa");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 140, -1));

        tbCari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbCari.setText("Cari");
        tbCari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCariActionPerformed(evt);
            }
        });
        jPanel1.add(tbCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 70, 30));

        tFirstName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 190, -1));

        tLastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 190, -1));

        tUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 190, -1));

        tJumlahBeli.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tJumlahBeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, 190, -1));

        tKodeMotor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tKodeMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 110, -1));

        tNamaMotor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tNamaMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 190, -1));

        tWarnaMotor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tWarnaMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 190, -1));

        tTahunMotor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tTahunMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 190, -1));

        tHargaMotor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tHargaMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 190, -1));

        tTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 190, -1));

        totalSisa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(totalSisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 190, -1));

        tbTambah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbTambah.setText("Tambah");
        tbTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTambahActionPerformed(evt);
            }
        });
        jPanel1.add(tbTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 110, 30));

        tbLihat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbLihat.setText("Cetak");
        tbLihat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbLihatActionPerformed(evt);
            }
        });
        jPanel1.add(tbLihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, 80, 30));

        tbHapus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbHapus.setText("Hapus");
        tbHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapusActionPerformed(evt);
            }
        });
        jPanel1.add(tbHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 80, 30));

        tbHitung.setText("Hitung");
        tbHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHitungActionPerformed(evt);
            }
        });
        jPanel1.add(tbHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 120, -1));

        tbKirim.setText("Send");
        tbKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbKirimActionPerformed(evt);
            }
        });
        jPanel1.add(tbKirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 260, 120, -1));

        pilihPembayaran.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pilihPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "ATM", "TUNAI" }));
        pilihPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihPembayaranActionPerformed(evt);
            }
        });
        jPanel1.add(pilihPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 220, 160, -1));

        tabelPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelPemesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelPemesanan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 960, 220));

        transfer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(transfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 190, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/transparent-black-png-3.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 980, 630));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/glatarbelakang2.jpg"))); // NOI18N
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHomeMouseClicked
        // TODO add your handling code here:
        this.hide();
        mLoginPembeli login = new mLoginPembeli();
        login.setVisible(true);
    }//GEN-LAST:event_tbHomeMouseClicked

    private void tbCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCariActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "SELECT * FROM daftarmotor WHERE "+"kode_motor='"+tKodeMotor.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.koneksiDB.myDB();
            java.sql.Statement st = conn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                tKodeMotor.setText(rs.getString("kode_motor"));
                tNamaMotor.setText(rs.getString("nama_motor"));
                tWarnaMotor.setText(rs.getString("warna_motor"));
                tTahunMotor.setText(rs.getString("tahun"));
                tHargaMotor.setText(rs.getString("Harga_motor"));
                tbTambah.setEnabled(false);
                tJumlahBeli.setEnabled(true);
                tTotal.setEnabled(false);
                tbHitung.setEnabled(true);
                
                pilihPembayaran.setEnabled(false);
                transfer.setEnabled(false);
                tbKirim.setEnabled(false);
                totalSisa.setEnabled(false);
            }else{
                showData();
                JOptionPane.showMessageDialog(rootPane, "Kode Motor tidak ditemukan!");
                bersihkanlayar();
                tKodeMotor.requestFocus();
            }showData();
        }catch(SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_tbCariActionPerformed

    private void tbTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTambahActionPerformed
        // TODO add your handling code here:
         
        try{
            
            String sql = "INSERT INTO tabel_pesan VALUES ('"+tNo_Pesanan.getText()+"','"+tFirstName.getText()+"','"+tLastName.getText()+"','"+tUsername.getText()+"','"+tKodeMotor.getText()+"','"+tNamaMotor.getText()+"','"+tWarnaMotor.getText()+"','"+tTahunMotor.getText()+ "','"+tHargaMotor.getText()+"','"+tJumlahBeli.getText()+"','"+tTotal.getText()+"','"+pilihPembayaran.getSelectedItem()+"','"+transfer.getText()+"','"+totalSisa.getText()+"')";
//            String sql = "INSERT INTO tabel_pesan" + "(no,first_name,last_name,username_pembeli,kode_motor,nama_motor,warna_motor,tahun,harga_motor,jumlah_dipesan, total,metode_pembayaran,input_uang,total_sisa)"+" VALUE (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            java.sql.Connection conn = (Connection)koneksi.koneksiDB.myDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            
            pstm.executeUpdate();
            showData();
            getID();
            bersihkanlayar();
            JOptionPane.showMessageDialog(null, "Telah terdata, silahkan Lihat data anda");
        }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_tbTambahActionPerformed

    private void tbLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbLihatActionPerformed
        // TODO add your handling code here:
        this.hide();
        cetak_struk pembeli = new cetak_struk();
        pembeli.setVisible(true);
    }//GEN-LAST:event_tbLihatActionPerformed

    private void tbResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbResetActionPerformed
        // TODO add your handling code here:
        bersihkanlayar();
    }//GEN-LAST:event_tbResetActionPerformed

    private void tbKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbKirimActionPerformed
        // TODO add your handling code here:
        try{
        if(tFirstName.getText().equals(" ") && tLastName.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Nama Wajib diisi");
            tFirstName.requestFocus();
            tLastName.requestFocus();
        }else if(transfer.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Isi total uang transfermu");
            transfer.requestFocus();
        }else{
            int x,y,z;
            x=Integer.parseInt(tTotal.getText());
            y=Integer.parseInt(transfer.getText());
            z=y-x;
            if (y<x){
                JOptionPane.showMessageDialog(rootPane, "Uang tidak cukup");
                transfer.setText("");
            }else{
                totalSisa.setText(String.valueOf(z));
               JOptionPane.showMessageDialog(rootPane, "Berhasil,silahkan klik tombol Tambah");
               tbTambah.setEnabled(true);
                }
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    
    }//GEN-LAST:event_tbKirimActionPerformed

    private void tbHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHitungActionPerformed
        // TODO add your handling code here:
        double a,b;
        int c;
        a = Double.parseDouble(tHargaMotor.getText());
        b = Double.parseDouble(tJumlahBeli.getText());
        c = (int)(a*b);
        tTotal.setText(String.valueOf(c));
        
        tbTambah.setEnabled(false);
        tJumlahBeli.setEnabled(true);
        tTotal.setEnabled(false);
        tbHitung.setEnabled(true);
        pilihPembayaran.setEnabled(true);
        transfer.setEnabled(false);
        tbKirim.setEnabled(false);
        totalSisa.setEnabled(false);
    }//GEN-LAST:event_tbHitungActionPerformed

    private void pilihPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihPembayaranActionPerformed
        // TODO add your handling code here:
        try{
            if(pilihPembayaran.getSelectedItem()=="ATM"){
                
                tbTambah.setEnabled(false);
                tJumlahBeli.setEnabled(true);
                tTotal.setEnabled(false);
                tbHitung.setEnabled(true);
                pilihPembayaran.setEnabled(true);
                transfer.setEnabled(true);
                tbKirim.setEnabled(true);
                totalSisa.setEnabled(false);
            }else if(pilihPembayaran.getSelectedItem()=="TUNAI"){
                
                tbTambah.setEnabled(false);
                tJumlahBeli.setEnabled(true);
                tTotal.setEnabled(false);
                tbHitung.setEnabled(true);
                pilihPembayaran.setEnabled(true);
                transfer.setEnabled(true);
                tbKirim.setEnabled(true);
                totalSisa.setEnabled(false);
            }else if(pilihPembayaran.getSelectedItem()=="Pilih"){
                
                tbTambah.setEnabled(false);
                tJumlahBeli.setEnabled(true);
                tTotal.setEnabled(false);
                tbHitung.setEnabled(true);
                pilihPembayaran.setEnabled(true);
                transfer.setEnabled(false);
                tbKirim.setEnabled(false);
                totalSisa.setEnabled(false);
            }
        }catch(Exception ex){
           JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_pilihPembayaranActionPerformed

    private void tbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapusActionPerformed
        // TODO add your handling code here:
         try{
            String sql = "DELETE FROM tabel_pesan WHERE no ='"+tNo_Pesanan.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.koneksiDB.myDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Berhasil dihapus!");
            showData();
            bersihkanlayar();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Gagal dihapus!"+ex.getMessage());
        }
    }//GEN-LAST:event_tbHapusActionPerformed

    private void tabelPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelPemesananMouseClicked
        // TODO add your handling code here:
        int tb_pesan = tabelPemesanan.getSelectedRow();
        tNo_Pesanan.setText(tabelPemesanan.getValueAt(tb_pesan, 0).toString());
        tFirstName.setText(tabelPemesanan.getValueAt(tb_pesan, 1).toString());
        tLastName.setText(tabelPemesanan.getValueAt(tb_pesan, 2).toString());
        tUsername.setText(tabelPemesanan.getValueAt(tb_pesan, 3).toString());
        tKodeMotor.setText(tabelPemesanan.getValueAt(tb_pesan, 4).toString());
        tNamaMotor.setText(tabelPemesanan.getValueAt(tb_pesan, 5).toString());
        tWarnaMotor.setText(tabelPemesanan.getValueAt(tb_pesan, 6).toString());
        tTahunMotor.setText(tabelPemesanan.getValueAt(tb_pesan, 7).toString());
        tHargaMotor.setText(tabelPemesanan.getValueAt(tb_pesan, 8).toString());
        tJumlahBeli.setText(tabelPemesanan.getValueAt(tb_pesan, 9).toString());
        tTotal.setText(tabelPemesanan.getValueAt(tb_pesan, 10).toString());
        pilihPembayaran.setSelectedItem(tabelPemesanan.getValueAt(tb_pesan, 11).toString());
        transfer.setText(tabelPemesanan.getValueAt(tb_pesan, 12).toString());
        totalSisa.setText(tabelPemesanan.getValueAt(tb_pesan, 13).toString());
        
        
    }//GEN-LAST:event_tabelPemesananMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mPesan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mPesan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> pilihPembayaran;
    private javax.swing.JTextField tFirstName;
    private javax.swing.JTextField tHargaMotor;
    private javax.swing.JTextField tJumlahBeli;
    private javax.swing.JTextField tKodeMotor;
    private javax.swing.JTextField tLastName;
    private javax.swing.JTextField tNamaMotor;
    private javax.swing.JTextField tNo_Pesanan;
    private javax.swing.JTextField tTahunMotor;
    private javax.swing.JTextField tTotal;
    private javax.swing.JTextField tUsername;
    private javax.swing.JTextField tWarnaMotor;
    private javax.swing.JTable tabelPemesanan;
    private javax.swing.JButton tbCari;
    private javax.swing.JButton tbHapus;
    private javax.swing.JButton tbHitung;
    private javax.swing.JLabel tbHome;
    private javax.swing.JButton tbKirim;
    private javax.swing.JButton tbLihat;
    private javax.swing.JButton tbReset;
    private javax.swing.JButton tbTambah;
    private javax.swing.JTextField totalSisa;
    private javax.swing.JTextField transfer;
    // End of variables declaration//GEN-END:variables
}
