/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class mTambahMotor extends javax.swing.JFrame {

    /**
     * Creates new form mTambahMotor
     */
    public mTambahMotor() {
        initComponents();
        showData();
        bersihkanlayar();
    }
    
    private void bersihkanlayar(){
        
        tKodeMotor.requestFocus();
        tNamaMotor.setText("");
        tWarnaMotor.setText("");
        tTahun.setText("");
        tMerk.setText("");
        tHargaMotor.setText("");
        tUsernamePegawai.setText("");
    
        
    }
    
    private void showData(){
     DefaultTableModel tabelM = new DefaultTableModel();
     tabelM.addColumn("Kode Motor");
     tabelM.addColumn("Nama Motor");
     tabelM.addColumn("Warna");
     tabelM.addColumn("Tahun");
     tabelM.addColumn("Merk");
     tabelM.addColumn("Harga");
     tabelM.addColumn("Username Penginput");
     
     try{
         String sql = "SELECT * FROM daftarmotor ORDER by kode_motor DESC";
         java.sql.Connection conn = (Connection)koneksi.koneksiDB.myDB();
         java.sql.Statement stm = conn.createStatement();
         java.sql.ResultSet rs = stm.executeQuery(sql);
         while(rs.next())
         {
             tabelM.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),});
         }tabelMotor.setModel(tabelM);
     }catch(SQLException ex){
         JOptionPane.showMessageDialog(rootPane, "Gagal disimpan!"+ex.getMessage());
     }
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMotor = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        tKodeMotor = new javax.swing.JTextField();
        tTahun = new javax.swing.JTextField();
        tMerk = new javax.swing.JTextField();
        tNamaMotor = new javax.swing.JTextField();
        tWarnaMotor = new javax.swing.JTextField();
        tHargaMotor = new javax.swing.JTextField();
        tUsernamePegawai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tbTambah = new javax.swing.JButton();
        tbUpdate = new javax.swing.JButton();
        tbHapus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tbBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(840, 460));
        setMinimumSize(new java.awt.Dimension(840, 460));
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(840, 541));
        jPanel1.setMinimumSize(new java.awt.Dimension(840, 541));
        jPanel1.setPreferredSize(new java.awt.Dimension(840, 541));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelMotor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelMotor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMotorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelMotor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 820, 140));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setText("KODE MOTOR");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        tKodeMotor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tKodeMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 150, -1));

        tTahun.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 90, -1));

        tMerk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tMerk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 210, -1));

        tNamaMotor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tNamaMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 210, -1));

        tWarnaMotor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tWarnaMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 210, -1));

        tHargaMotor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tHargaMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 210, -1));

        tUsernamePegawai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tUsernamePegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 210, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("NAMA MOTOR");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setText("WARNA MOTOR");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setText("TAHUN");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 60, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setText("MERK");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 60, -1));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setText("HARGA");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 70, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel10.setText("USERNAME PEGAWAI");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, -1, -1));

        tbTambah.setText("TAMBAH");
        tbTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTambahActionPerformed(evt);
            }
        });
        jPanel1.add(tbTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 100, 40));

        tbUpdate.setText("UPDATE");
        tbUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(tbUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 100, 40));

        tbHapus.setText("HAPUS");
        tbHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapusActionPerformed(evt);
            }
        });
        jPanel1.add(tbHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 100, 40));

        jPanel3.setBackground(new java.awt.Color(12, 36, 97));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TAMBAH MOTOR");

        tbBack.setBackground(new java.awt.Color(255, 77, 77));
        tbBack.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tbBack.setForeground(new java.awt.Color(255, 255, 255));
        tbBack.setText("BACK");
        tbBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(180, 180, 180)
                .addComponent(tbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/gtrans1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 820, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/glatarbelakang2.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(840, 541));
        jLabel1.setMinimumSize(new java.awt.Dimension(840, 541));
        jLabel1.setPreferredSize(new java.awt.Dimension(840, 541));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBackActionPerformed
        // TODO add your handling code here:
        this.hide();
        mLoginPegawai back = new mLoginPegawai();
        back.setVisible(true);
    }//GEN-LAST:event_tbBackActionPerformed

    private void tbTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTambahActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "INSERT INTO daftarmotor (kode_motor,nama_motor,warna_motor,tahun,merk_motor,harga_motor,username_pegawai)"+"VALUES(?,?,?,?,?,?,?)";
            java.sql.Connection conn = (Connection)koneksi.koneksiDB.myDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.setString(1, tKodeMotor.getText().trim());
            pstm.setString(2, tNamaMotor.getText().trim());
            pstm.setString(3, tWarnaMotor.getText().trim());
            pstm.setString(4, tTahun.getText().trim());
            pstm.setString(5, tMerk.getText().trim());
            pstm.setString(6, tHargaMotor.getText().trim());
            pstm.setString(7, tUsernamePegawai.getText().trim());
            pstm.execute();
            JOptionPane.showMessageDialog(rootPane, "Berhasil disimpan!");
            showData();
            bersihkanlayar();
        
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Gagal disimpan!"+ex.getMessage());
        }
    }//GEN-LAST:event_tbTambahActionPerformed

    private void tbUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbUpdateActionPerformed
        // TODO add your handling code here:
        try{
            
            String sql = "UPDATE daftarmotor SET kode_motor ='"+tKodeMotor.getText()+"',nama_motor ='"+tNamaMotor.getText()+"',warna_motor ='"+tWarnaMotor.getText()+"',tahun ='"+tTahun.getText()+"',merk_motor ='"+tMerk.getText()+"',harga_motor ='"+tHargaMotor.getText()+"',username_pegawai ='"+tUsernamePegawai.getText()+"' WHERE kode_motor='"+tKodeMotor.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.koneksiDB.myDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            
            pstm.executeUpdate();
            
            showData();
            bersihkanlayar();
        JOptionPane.showMessageDialog(rootPane, "Berhasil diupdate!");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Gagal disimpan!"+ex.getMessage());
        }
    }//GEN-LAST:event_tbUpdateActionPerformed

    private void tabelMotorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMotorMouseClicked
        // TODO add your handling code here:
        tKodeMotor.setEnabled(false);
        int tb_motor = tabelMotor.getSelectedRow();
        tKodeMotor.setText(tabelMotor.getValueAt(tb_motor, 0).toString());
        tNamaMotor.setText(tabelMotor.getValueAt(tb_motor, 1).toString());
        tWarnaMotor.setText(tabelMotor.getValueAt(tb_motor, 2).toString());
        tTahun.setText(tabelMotor.getValueAt(tb_motor, 3).toString());
        tMerk.setText(tabelMotor.getValueAt(tb_motor, 4).toString());
        tHargaMotor.setText(tabelMotor.getValueAt(tb_motor, 5).toString());
        tUsernamePegawai.setText(tabelMotor.getValueAt(tb_motor, 6).toString());
    }//GEN-LAST:event_tabelMotorMouseClicked

    private void tbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapusActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "DELETE FROM daftarmotor WHERE kode_motor='"+tKodeMotor.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.koneksiDB.myDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.executeUpdate();
            JOptionPane.showMessageDialog(rootPane, "Berhasil dihapus!");
            showData();
            bersihkanlayar();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Gagal disimpan!"+ex.getMessage());
        }
    }//GEN-LAST:event_tbHapusActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        tKodeMotor.setEnabled(true);
        bersihkanlayar();
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mTambahMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mTambahMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mTambahMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mTambahMotor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mTambahMotor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tHargaMotor;
    private javax.swing.JTextField tKodeMotor;
    private javax.swing.JTextField tMerk;
    private javax.swing.JTextField tNamaMotor;
    private javax.swing.JTextField tTahun;
    private javax.swing.JTextField tUsernamePegawai;
    private javax.swing.JTextField tWarnaMotor;
    private javax.swing.JTable tabelMotor;
    private javax.swing.JButton tbBack;
    private javax.swing.JButton tbHapus;
    private javax.swing.JButton tbTambah;
    private javax.swing.JButton tbUpdate;
    // End of variables declaration//GEN-END:variables
}
