/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package code;

import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class mDaftarPembeli extends javax.swing.JFrame {

    /**
     * Creates new form mDaftarPesanandanPembeli
     */
    public mDaftarPembeli() {
        initComponents();
        showDataPegawai();
        bersihkanlayar();
    }
    
    private void bersihkanlayar(){
        
        tUsername.setText("");
        tPassword.setText("");
        tEmail.setText("");
        
         tUsername.setEnabled(false);
        tPassword.setEnabled(false);
        tEmail.setEnabled(false);
    }
    
    private void showDataPegawai(){
        
        DefaultTableModel tabelPembeli = new DefaultTableModel(); 
        tabelPembeli.addColumn("Username");
        tabelPembeli.addColumn("Password");
        tabelPembeli.addColumn("Email");
        try{
           
            String sql = "SELECT * FROM pembeli";
            java.sql.Connection conn = (Connection)koneksi.koneksiDB.myDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                tabelPembeli.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3)});
                
            }tbPegawai.setModel(tabelPembeli);
        }catch (SQLException ex){
            System.out.println("Error = " + ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tbBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPegawai = new javax.swing.JTable();
        tEmail = new javax.swing.JTextField();
        tUsername = new javax.swing.JTextField();
        tPassword = new javax.swing.JTextField();
        tbHapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(760, 360));

        jPanel1.setMaximumSize(new java.awt.Dimension(760, 360));
        jPanel1.setMinimumSize(new java.awt.Dimension(760, 360));
        jPanel1.setPreferredSize(new java.awt.Dimension(760, 360));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(12, 36, 97));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DAFTAR PEMBELI");

        tbBack.setBackground(new java.awt.Color(255, 77, 77));
        tbBack.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        tbBack.setForeground(new java.awt.Color(255, 255, 255));
        tbBack.setText("KEMBALI");
        tbBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(252, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(147, 147, 147)
                .addComponent(tbBack, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 90));

        tbPegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPegawaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbPegawai);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 730, 110));
        jPanel1.add(tEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 230, -1));
        jPanel1.add(tUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 230, -1));
        jPanel1.add(tPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 230, -1));

        tbHapus.setBackground(new java.awt.Color(255, 77, 77));
        tbHapus.setText("HAPUS");
        tbHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapusActionPerformed(evt);
            }
        });
        jPanel1.add(tbHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 100, 46));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Username");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/transparent-black-png-3.png"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(830, 460));
        jLabel3.setMinimumSize(new java.awt.Dimension(830, 460));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 740, 320));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/glatarbelakang2.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(760, 360));
        jLabel2.setMinimumSize(new java.awt.Dimension(760, 360));
        jLabel2.setPreferredSize(new java.awt.Dimension(760, 360));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBackActionPerformed
        // TODO add your handling code here:
        this.hide();
        mLoginPegawai back = new mLoginPegawai();
        back.setVisible(true);
    }//GEN-LAST:event_tbBackActionPerformed

    private void tbPegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPegawaiMouseClicked
        // TODO add your handling code here:
        int daftar_pegawai = tbPegawai.getSelectedRow();
        tUsername.setText(tbPegawai.getValueAt(daftar_pegawai, 0).toString());
        tPassword.setText(tbPegawai.getValueAt(daftar_pegawai, 1).toString());
        tEmail.setText(tbPegawai.getValueAt(daftar_pegawai, 2).toString());
    
    }//GEN-LAST:event_tbPegawaiMouseClicked

    private void tbHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapusActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "DELETE FROM pembeli WHERE username_pembeli='"+tUsername.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.koneksiDB.myDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.executeUpdate();
            
            showDataPegawai();
            bersihkanlayar();
            JOptionPane.showMessageDialog(rootPane, "Berhasil dihapus!");
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Gagal dihapus!"+ex.getMessage());
        }
    }//GEN-LAST:event_tbHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mDaftarPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mDaftarPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mDaftarPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mDaftarPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mDaftarPembeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tPassword;
    private javax.swing.JTextField tUsername;
    private javax.swing.JButton tbBack;
    private javax.swing.JButton tbHapus;
    private javax.swing.JTable tbPegawai;
    // End of variables declaration//GEN-END:variables
}
